//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hack4Edu.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hack4Edu.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art.
        /// </summary>
        internal static string ArtText {
            get {
                return ResourceManager.GetString("ArtText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account.
        /// </summary>
        internal static string CreateAccountButtonText {
            get {
                return ResourceManager.GetString("CreateAccountButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are required..
        /// </summary>
        internal static string CreateAccountErrorBodyText {
            get {
                return ResourceManager.GetString("CreateAccountErrorBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string CreateAccountErrorButtonText {
            get {
                return ResourceManager.GetString("CreateAccountErrorButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string CreateAccountErrorTitleText {
            get {
                return ResourceManager.GetString("CreateAccountErrorTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account!.
        /// </summary>
        internal static string CreateAccountText {
            get {
                return ResourceManager.GetString("CreateAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string ForgotPasswordText {
            get {
                return ResourceManager.GetString("ForgotPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction to Relief.
        /// </summary>
        internal static string GeoAssignment1 {
            get {
                return ResourceManager.GetString("GeoAssignment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography.
        /// </summary>
        internal static string GeographyText {
            get {
                return ResourceManager.GetString("GeographyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? Log in.
        /// </summary>
        internal static string HaveAccountText {
            get {
                return ResourceManager.GetString("HaveAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancient Rome.
        /// </summary>
        internal static string HistAssignment1 {
            get {
                return ResourceManager.GetString("HistAssignment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The American Revolution.
        /// </summary>
        internal static string HistAssignment2 {
            get {
                return ResourceManager.GetString("HistAssignment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string HistoryText {
            get {
                return ResourceManager.GetString("HistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is incorrect. Please try again..
        /// </summary>
        internal static string LoginErrorBodyText {
            get {
                return ResourceManager.GetString("LoginErrorBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string LoginErrorButtonText {
            get {
                return ResourceManager.GetString("LoginErrorButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error.
        /// </summary>
        internal static string LoginErrorTitleText {
            get {
                return ResourceManager.GetString("LoginErrorTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to continue..
        /// </summary>
        internal static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition and Subtraction.
        /// </summary>
        internal static string MathAssignment1 {
            get {
                return ResourceManager.GetString("MathAssignment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication Tables.
        /// </summary>
        internal static string MathAssignment2 {
            get {
                return ResourceManager.GetString("MathAssignment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mathematics.
        /// </summary>
        internal static string MathematicsText {
            get {
                return ResourceManager.GetString("MathematicsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string MusicText {
            get {
                return ResourceManager.GetString("MusicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read time:.
        /// </summary>
        internal static string ReadTimeText {
            get {
                return ResourceManager.GetString("ReadTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Assignments.
        /// </summary>
        internal static string RemainingAssignmentsText {
            get {
                return ResourceManager.GetString("RemainingAssignmentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
